### ISSUE TITLE
Migration to Postgres & TypeORM

### ISSUE THREAD

**Issue by FreeLineTM** [dev-erse/Polaris#2]
### Postgres & TypeORM switch
As discussed in Discord with @Neztore and @MartinRBX, the Polaris project will make the switch from RethinkDB to Postgres with TypeORM. The reasoning behind this is that a SQL database will provide better scaling and easier implementations later down the line. The switch involves modifying the `Database` class (possibly removing it and using TypeORM calls everywhere) and setting up TypeORM models and migrations for production.

The table/model structure can be found on Vertabelo [here](https://my.vertabelo.com/doc/4zfyg43EYPOOYIwE8LIW8TNOLCcvhgQR). This requires an account with a limited trial, if access is required for an extended period of time we will find another alternative.

#### References
[PostgreSQL](https://www.postgresql.org/)
[TypeORM](http://typeorm.io)

**Comment by Neztore** [comment]
We decided to stick with rethink
